modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="mekaplus"
version="0.1.0"
displayName="MEKAPLUS MOD"
authors="HITEYY"
description='''
MEKAPLUS progression: Starlight, Soul Boss, Antigear, Antimatter Synthesizer, Vibranium.
'''
logoFile="logo.png"

[[dependencies.mekaplus]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mekaplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mekaplus]]
    modId="mekanism"
    mandatory=false
    versionRange="[10.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mekaplus]]
    modId="create"
    mandatory=false
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mekaplus]]
    modId="ae2"
    mandatory=false
    versionRange="[19.0,)"
    ordering="AFTER"
    side="BOTH"
